"""Attach labels to the dyad-week panel.

y_icb     : 1 if an ICB crisis involving this dyad has its trigger date in (t, t+H], H=30 days.
            NULL after `icb_last_complete_date` (ICB v16 is truncated; no label available).
in_crisis : 1 if t lies inside an ongoing ICB crisis for the dyad (onset <= t <= end).  These
            rows are excluded from model training / evaluation (neither a new onset nor a clean
            negative) but kept in the panel for the replay demo.
y_thresh  : 1 if material-conflict (QuadClass 4) events in the next 4 weeks >= threshold_ratio x
            the trailing-52-week mean 4-week count AND >= threshold_min_events.
Everything here uses only `q4_next4w` (forward sum computed in features.py) and ICB dates.
"""
import argparse
import os

import duckdb
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build(panel_path, icb_dyads, out_path, report_path, cfg, threads=8):
    H = cfg["labels"]["horizon_days"]
    ratio = cfg["labels"]["threshold_ratio"]
    min_ev = cfg["labels"]["threshold_min_events"]
    icb_last = cfg["labels"].get("icb_last_complete_date", "2021-12-31")
    con = duckdb.connect()
    con.execute(f"PRAGMA threads={threads}")
    con.execute(f"""
    CREATE TABLE icb AS
    SELECT crisno, dyad, min(onset_date) AS onset_date,
           coalesce(max(end_date), min(onset_date) + INTERVAL 365 DAY) AS end_date,
           any_value(crisname) AS crisname
    FROM read_parquet('{icb_dyads}')
    WHERE dyad IS NOT NULL AND onset_date IS NOT NULL
    GROUP BY crisno, dyad
    """)
    con.execute(f"CREATE TABLE p AS SELECT * FROM read_parquet('{panel_path}')")
    con.execute(f"""
    CREATE TABLE labelled AS
    SELECT p.*,
           CASE WHEN p.t > DATE '{icb_last}' - INTERVAL {H} DAY THEN NULL
                ELSE coalesce(o.y_icb, 0) END AS y_icb,
           o.next_crisno, o.next_crisname, o.next_onset,
           coalesce(c.in_crisis, 0) AS in_crisis, c.cur_crisno, c.cur_crisname,
           CASE WHEN p.q4_next4w IS NULL THEN NULL
                WHEN p.q4_next4w >= greatest({min_ev}, {ratio} * p.q4_base_4w) THEN 1 ELSE 0 END AS y_thresh
    FROM p
    LEFT JOIN (
        SELECT p.dyad, p.t, 1 AS y_icb, arg_min(i.crisno, i.onset_date) AS next_crisno,
               arg_min(i.crisname, i.onset_date) AS next_crisname, min(i.onset_date) AS next_onset
        FROM p JOIN icb i ON i.dyad = p.dyad AND i.onset_date > p.t AND i.onset_date <= p.t + INTERVAL {H} DAY
        GROUP BY p.dyad, p.t
    ) o USING (dyad, t)
    LEFT JOIN (
        SELECT p.dyad, p.t, 1 AS in_crisis, arg_min(i.crisno, i.onset_date) AS cur_crisno,
               arg_min(i.crisname, i.onset_date) AS cur_crisname
        FROM p JOIN icb i ON i.dyad = p.dyad AND i.onset_date <= p.t AND i.end_date >= p.t
        GROUP BY p.dyad, p.t
    ) c USING (dyad, t)
    """)
    con.execute(f"COPY labelled TO '{out_path}' (FORMAT PARQUET, COMPRESSION ZSTD)")

    # ---- report
    tot = con.execute("SELECT count(*) FROM labelled").fetchone()[0]
    bal = con.execute("""
    SELECT 'y_icb (all rows with label)' AS label, count(y_icb) AS n, sum(y_icb) AS pos,
           sum(y_icb)/count(y_icb) AS rate FROM labelled
    UNION ALL
    SELECT 'y_icb (excl. in_crisis rows)', count(y_icb), sum(y_icb), sum(y_icb)/count(y_icb)
      FROM labelled WHERE in_crisis=0
    UNION ALL
    SELECT 'y_icb (excl. in_crisis, regime_daily=1)', count(y_icb), sum(y_icb), sum(y_icb)/count(y_icb)
      FROM labelled WHERE in_crisis=0 AND regime_daily=1
    UNION ALL
    SELECT 'y_thresh (all rows)', count(y_thresh), sum(y_thresh), sum(y_thresh)/count(y_thresh) FROM labelled
    UNION ALL
    SELECT 'y_thresh (excl. in_crisis rows)', count(y_thresh), sum(y_thresh), sum(y_thresh)/count(y_thresh)
      FROM labelled WHERE in_crisis=0
    """).df()
    by_year = con.execute("""
    SELECT year, count(*) AS rows, sum(y_icb) AS icb_pos, count(DISTINCT next_crisno) AS icb_crises,
           sum(y_thresh) AS thresh_pos, sum(in_crisis) AS in_crisis_rows
    FROM labelled GROUP BY year ORDER BY year""").df()
    covered = con.execute("""
    SELECT count(DISTINCT i.crisno) AS covered, (SELECT count(DISTINCT crisno) FROM icb WHERE onset_date >= DATE '1979-01-01') AS total
    FROM icb i JOIN labelled l ON l.next_crisno = i.crisno""").df().iloc[0]
    missed = con.execute("""
    SELECT i.crisno, i.crisname, i.dyad, i.onset_date FROM icb i
    WHERE i.onset_date >= DATE '1979-01-01' AND i.crisno NOT IN (SELECT DISTINCT next_crisno FROM labelled WHERE next_crisno IS NOT NULL)
    ORDER BY onset_date""").df()
    md = [f"# Labels report", "", "Auto-generated by `labels/build_labels.py`.", "",
          f"Panel rows: {tot:,}.  Horizon H = {H} days (4 weekly steps).  "
          f"Secondary threshold: q4_next4w >= max({min_ev}, {ratio} x trailing-52w mean 4-week q4).", "",
          "## Class balance", "", bal.to_markdown(index=False, floatfmt=".5f"), "",
          f"## ICB coverage", "",
          f"ICB crisis dyads with onset >= 1979 that appear as a positive label in the panel: "
          f"**{int(covered.covered)} / {int(covered.total)}**.  Crises are missed when the dyad has a "
          f"pre-1979 start only, when an actor has no GDELT code, or when the dyad's first GDELT "
          f"activity is after the onset.", ""]
    if len(missed):
        md += ["### ICB crisis-dyads (onset >= 1979) not reached by any positive panel row", "",
               missed.to_markdown(index=False), ""]
    md += ["## By year", "", by_year.to_markdown(index=False), ""]
    with open(report_path, "w") as f:
        f.write("\n".join(md))
    print("\n".join(md[:12]))
    con.close()


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--panel", default=os.path.join(ROOT, "data", "processed", "panel", "panel.parquet"))
    ap.add_argument("--icb-dyads", default=os.path.join(ROOT, "data", "processed", "icb", "dyads.parquet"))
    ap.add_argument("--out", default=os.path.join(ROOT, "data", "processed", "panel", "panel_labelled.parquet"))
    ap.add_argument("--report", default=os.path.join(ROOT, "docs", "labels_report.md"))
    ap.add_argument("--threads", type=int, default=8)
    args = ap.parse_args()
    with open(os.path.join(ROOT, "config.yaml")) as f:
        cfg = yaml.safe_load(f)
    build(args.panel, args.icb_dyads, args.out, args.report, cfg, args.threads)
